### PR TITLE
added link variant for buttons

### PR DESCRIPTION
**Pull request by MeenuKumari28**
added link variant for buttons.
link-button

### CODE REVIEW

**Comment by amitu** [comment]
Warning looks a bit too much like primary, can you show both?

**Comment by MeenuKumari28** [comment]
@amitu 
warning

**Comment by amitu** [comment]
Primary button is not readable at all.

**Comment by MeenuKumari28** [comment]
@amitu that is because of the primary text color value we have given inside our color scheme. What color do you want there instead of the primary text color?

**Comment by amitu** [comment]
> What color do you want there instead of the primary text color?

@yashveer29, please help here.

**Comment by MeenuKumari28** [comment]
@amitu This is the updated color for the primary button
button-color

**Comment by amitu** [comment]
@MeenuKumari28 can you show how other primary button looks? Is the white color only for `variant: link` or everything?

**Comment by amitu** [comment]
Show other variants of primary-button I meant. Also update your docs to show this in one place. User should not have to guess how this looks in different situations. Also you can put all the variant in one row, you do not have to show source code for everything.

**Comment by amitu** [comment]
@MeenuKumari28 share final screenshot as well.

**Comment by MeenuKumari28** [comment]
@amitu Final screensort for the 
all-variant
button.

**Pull request merged**
