### PR TITLE
added border width and radius

### PR DESCRIPTION
**Pull request by MeenuKumari28**
added border width and radius

### CODE REVIEW

**Comment by amitu** [comment]
@MeenuKumari28 I need documentation of every property, and example code/demo with that feature. Include first add the docs etc and then add the screenshot in the PR.

**Comment by MeenuKumari28** [comment]
@amitu documentation for every property is added.
section-column
section-row
row
container
column

**Comment by amitu** [comment]
@MeenuKumari28 in the docs for all container components, eg `ds.row`, `ds.section-row` etc, do include some children as well, right now they look like rectangles, not containers.

**Comment by MeenuKumari28** [comment]
@amitu Updated doc for column, row etc.
section-column-eg
section-row-eg
row-eg
container-eg
column-eg

**Pull request merged**
