### PR TITLE
added alert component

### PR DESCRIPTION
**Pull request by MeenuKumari28**
added alert component
alert
toggle

### CODE REVIEW

**Comment by amitu** [comment]
@MeenuKumari28 what all values of kind is supported? Show all screenshots.

**Comment by amitu** [comment]
Also alert is not a form element.

**Comment by MeenuKumari28** [comment]
> @MeenuKumari28 what all values of kind is supported? Show all screenshots.

@amitu 
danger-alert
success-alert
warning-alert
alert

**Comment by MeenuKumari28** [comment]
> Also alert is not a form element.

@amitu can we put alert inside a popup element?

**Comment by amitu** [comment]
But does it popup? Look at other design systems, and try to take inspirations. We are not creating a design system for the first time in the world.

**Comment by amitu** [comment]
@MeenuKumari28 not sure I like this. Everything in this package is a component, so they should all be put inside components folder. Is header not a component? Is row not a component? 

Leave form as form as form related components are needed when I am creating a form, and this is useful namespace. If you do not have a great namespace, you can put it in top level.

**Comment by yashveer29** [comment]
TreeView
@amitu what do you think about this structure

**Comment by amitu** [comment]
Works.

**Review by yashveer29 — APPROVED** [review]

**Comment by yashveer29** [comment]
@amitu please check this PR

**Comment by amitu** [comment]
@yashveer29 both for the toggle button and the checkbox earlier, you should add a label.

**Comment by yashveer29** [comment]
> @yashveer29 both for the toggle button and the checkbox earlier, you should add a label.

Do mean something like this ??
Screenshot 2024-02-01 at 5 09 04 PM

**Comment by amitu** [comment]
Yep

**Comment by yashveer29** [comment]
> Yep

@MeenuKumari28 we need to add this also

**Comment by MeenuKumari28** [comment]
> @yashveer29 both for the toggle button and the checkbox earlier, you should add a label.
@amitu @yashveer29 

checkbox-text
toggle-text

**Pull request merged**
